// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Ethers = require("ethers");

function fromUnsafe(prim) {
  return Ethers.BigNumber.from(prim);
}

function fromInt(prim) {
  return Ethers.BigNumber.from(prim);
}

var oneGweiInWei = Ethers.BigNumber.from(1000000000);

var zeroBN = Ethers.BigNumber.from(0);

var fourBN = Ethers.BigNumber.from(4);

var tenToThe2 = Ethers.BigNumber.from(100);

var tenToThe4 = Ethers.BigNumber.from(10000);

var tenToThe15 = Ethers.BigNumber.from("1000000000000000");

var tenToThe18 = Ethers.BigNumber.from("1000000000000000000");

var tenToThe9 = oneGweiInWei;

exports.fromUnsafe = fromUnsafe;
exports.fromInt = fromInt;
exports.oneGweiInWei = oneGweiInWei;
exports.zeroBN = zeroBN;
exports.fourBN = fourBN;
exports.tenToThe2 = tenToThe2;
exports.tenToThe4 = tenToThe4;
exports.tenToThe9 = tenToThe9;
exports.tenToThe15 = tenToThe15;
exports.tenToThe18 = tenToThe18;
/* oneGweiInWei Not a pure module */
