// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var ConfigurationJs = require("./config/configuration.js");

var polygonConfig = ConfigurationJs.polygon;

var chainId = 137;

exports.chainId = chainId;
exports.polygonConfig = polygonConfig;
/* polygonConfig Not a pure module */
