// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var Ethers = require("ethers");
var SecretsManagerJs = require("../secretsManager.js");
var Ethers$FloatJsClient = require("./demo/Ethers.js");
var MarketSide$FloatJsClient = require("./MarketSide.js");

var env = process.env;

var mnemonic = SecretsManagerJs.mnemonic;

var providerUrl = SecretsManagerJs.providerUrl;

function connectToNewWallet(provider, mnemonic) {
  return new (Ethers.Wallet.fromMnemonic)(mnemonic, "m/44'/60'/0'/0/0").connect(provider);
}

function run(param) {
  var $$float = MarketSide$FloatJsClient.MarketSide.newFloatMarketSide(Ethers$FloatJsClient.getSigner(connectToNewWallet(new (Ethers.providers.JsonRpcProvider)(providerUrl, 137), mnemonic)), Ethers.BigNumber.from(1), false);
  Curry._1($$float.getUnconfirmedExposure, undefined).then(function (a) {
        console.log(a.toString());
        
      });
  Curry._1($$float.getExposure, undefined).then(function (a) {
        console.log(a.toString());
        
      });
  
}

run(undefined);

exports.env = env;
exports.mnemonic = mnemonic;
exports.providerUrl = providerUrl;
exports.connectToNewWallet = connectToNewWallet;
exports.run = run;
/* env Not a pure module */
