// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var FloatChain = require("./FloatChain.js");

function make(param) {
  return {
          getChainWithProvider: FloatChain.makeWithProvider,
          getChainWithWallet: FloatChain.makeWithWallet,
          getChain: FloatChain.makeWithDefaultProvider
        };
}

exports.make = make;
/* FloatChain Not a pure module */
