// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Ethers = require("ethers");
var FloatConfig = require("@float-capital/config/src/FloatConfig.js");
var Float__Chain = require("./Float__Chain.js");
var Float__Ethers = require("./Float__Ethers.js");
var Float__Market = require("./Float__Market.js");
var Float__MarketSide = require("./Float__MarketSide.js");
var SecretsManagerJs = require("../secretsManager.js");

var env = process.env;

var mnemonic = SecretsManagerJs.mnemonic;

var providerUrlOther = SecretsManagerJs.providerUrl;

var oneGweiInWei = Float__Ethers.BigNumber.oneGweiInWei;

function fromInt(prim) {
  return Ethers.BigNumber.from(prim);
}

function connectToNewWallet(provider, mnemonic) {
  return new (Ethers.Wallet.fromMnemonic)(mnemonic, "m/44'/60'/0'/0/0").connect(provider);
}

var providerUrl = FloatConfig.avalancheConfig.rpcEndpoint;

var chainId = FloatConfig.avalancheConfig.networkId;

var provider = new (Ethers.providers.JsonRpcProvider)(providerUrl, chainId);

var wallet = connectToNewWallet(new (Ethers.providers.JsonRpcProvider)(providerUrl, chainId), mnemonic);

var maxFeePerGas = Ethers.BigNumber.from(62).mul(oneGweiInWei);

var maxPriorityFeePerGas = Ethers.BigNumber.from(34).mul(oneGweiInWei);

var gasLimit = Ethers.BigNumber.from(1000000);

var txOptions_maxFeePerGas = maxFeePerGas.toString();

var txOptions_maxPriorityFeePerGas = maxPriorityFeePerGas.toString();

var txOptions_gasLimit = gasLimit.toString();

var txOptions = {
  maxFeePerGas: txOptions_maxFeePerGas,
  maxPriorityFeePerGas: txOptions_maxPriorityFeePerGas,
  gasLimit: txOptions_gasLimit
};

function demoReadyOnly(param) {
  wallet.getBalance().then(function (balance) {
        console.log("Account balance:", Float__Ethers.Utils.formatEther(balance));
        
      });
  var sideName = "long";
  var chain = Float__Chain.WithProvider.makeDefault(chainId);
  Float__Chain.contracts(chain).then(function (c) {
        console.log("LongShort address:", c.longShort.address);
        
      });
  var market = Float__Market.WithProvider.make(provider, 1);
  Float__Market.fundingRateMultiplier(market).then(function (a) {
        console.log("Funding rate multiplier for market ".concat((1).toString()).concat(":"), a);
        
      });
  Float__Market.leverage(market).then(function (m) {
        console.log("Leverage for market ".concat((1).toString()).concat(":"), m);
        
      });
  var marketSide = Float__MarketSide.makeUsingMarket(market, true);
  Float__MarketSide.poolValue(marketSide).then(function (a) {
        console.log("Value of marketSide ".concat(sideName).concat(":"), a.toString());
        
      });
  Float__MarketSide.fundingRateApr(marketSide).then(function (a) {
        console.log("Funding rate APR for marketSide ".concat(sideName).concat(":"), a);
        
      });
  Float__MarketSide.exposure(marketSide).then(function (a) {
        console.log("Exposure of marketSide".concat(sideName).concat(":"), a.toString());
        
      });
  Float__MarketSide.unconfirmedExposure(marketSide).then(function (a) {
        console.log("Unconfirmed exposure of marketSide".concat(sideName).concat(":"), a.toString());
        
      });
  Float__MarketSide.positions(marketSide, "0x380d3d688fd65ef6858f0e094a1a9bba03ad76a3", undefined).then(function (a) {
        console.log("Synth token amount for 0x38.. in marketSide".concat(sideName).concat(":"), a.syntheticToken.toString());
        
      });
  
}

function demoWrite(param) {
  Float__Chain.WithWallet.make(wallet);
  var market = Float__Market.WithWallet.makeUnwrapped(wallet, 1);
  Float__Market.settleOutstandingActions(market, undefined, txOptions).then(function (tx) {
        console.log(tx.hash);
        
      });
  
}

demoReadyOnly(undefined);

exports.env = env;
exports.mnemonic = mnemonic;
exports.providerUrlOther = providerUrlOther;
exports.oneGweiInWei = oneGweiInWei;
exports.fromInt = fromInt;
exports.connectToNewWallet = connectToNewWallet;
exports.providerUrl = providerUrl;
exports.chainId = chainId;
exports.provider = provider;
exports.wallet = wallet;
exports.maxFeePerGas = maxFeePerGas;
exports.maxPriorityFeePerGas = maxPriorityFeePerGas;
exports.gasLimit = gasLimit;
exports.txOptions = txOptions;
exports.demoReadyOnly = demoReadyOnly;
exports.demoWrite = demoWrite;
/* env Not a pure module */
