// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var Chain;

var Market;

var MarketSide;

var Config;

exports.Chain = Chain;
exports.Market = Market;
exports.MarketSide = MarketSide;
exports.Config = Config;
/* No side effect */
