// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Ethers = require("ethers");
var FloatConfig = require("@float-dao/config/src/FloatConfig.js");

function getChainConfig(pw) {
  var tmp;
  tmp = pw.TAG === /* ProviderWrap */0 ? pw._0 : pw._0.provider;
  return tmp.getNetwork().then(function (network) {
              return FloatConfig.avalanche;
            });
}

function getChainConfigUsingId(chainId) {
  return FloatConfig.avalanche;
}

function makeDefaultProvider(c) {
  return new (Ethers.providers.JsonRpcProvider)(c.rpcEndopint, c.networkId);
}

exports.getChainConfig = getChainConfig;
exports.getChainConfigUsingId = getChainConfigUsingId;
exports.makeDefaultProvider = makeDefaultProvider;
/* ethers Not a pure module */
