// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function wrapMarketP(market) {
  return {
          TAG: /* P */0,
          _0: market
        };
}

function wrapMarketW(market) {
  return {
          TAG: /* W */1,
          _0: market
        };
}

exports.wrapMarketP = wrapMarketP;
exports.wrapMarketW = wrapMarketW;
/* No side effect */
