// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Ethers = require("ethers");
var Float__Util = require("./Float__Util.js");
var Float__Ethers = require("./Float__Ethers.js");
var Float__Contracts = require("./Float__Contracts.js");

function fromInt(prim) {
  return Ethers.BigNumber.from(prim);
}

function wrapChainP(side) {
  return {
          TAG: /* P */0,
          _0: side
        };
}

function wrapChainW(side) {
  return {
          TAG: /* W */1,
          _0: side
        };
}

function makeUnwrapped(p) {
  return {
          provider: p
        };
}

function make(p) {
  return {
          TAG: /* P */0,
          _0: {
            provider: p
          }
        };
}

function makeDefault(chainId) {
  var p = Float__Util.makeDefaultProvider(Float__Util.getChainConfigUsingId(chainId));
  return {
          TAG: /* P */0,
          _0: {
            provider: p
          }
        };
}

function makeDefaultUnwrapped(chainId) {
  return {
          provider: Float__Util.makeDefaultProvider(Float__Util.getChainConfigUsingId(chainId))
        };
}

var WithProvider = {
  makeUnwrapped: makeUnwrapped,
  make: make,
  makeDefault: makeDefault,
  makeDefaultUnwrapped: makeDefaultUnwrapped
};

function makeUnwrapped$1(w) {
  return {
          wallet: w
        };
}

function make$1(w) {
  return {
          TAG: /* W */1,
          _0: {
            wallet: w
          }
        };
}

var WithWallet = {
  makeUnwrapped: makeUnwrapped$1,
  make: make$1
};

function updateSystemStateMulti(wallet, config, marketIndexes) {
  var partial_arg = marketIndexes.map(function (i) {
        return Ethers.BigNumber.from(i);
      });
  var partial_arg$1 = Float__Util.makeLongShortContract(Float__Ethers.wrapWallet(wallet), config);
  return function (param) {
    return partial_arg$1.updateSystemStateMulti(partial_arg, param);
  };
}

function contracts(chain) {
  var tmp;
  tmp = chain.TAG === /* P */0 ? Float__Util.getChainConfig(Float__Ethers.wrapProvider(chain._0.provider)) : Float__Util.getChainConfig(Float__Ethers.wrapProvider(chain._0.wallet.provider));
  return tmp.then(function (c) {
              return c.contracts;
            });
}

function updateSystemStateMulti$1(chain, marketIndexes, txOptions) {
  return Float__Util.getChainConfig(Float__Ethers.wrapWallet(chain.wallet)).then(function (config) {
              return updateSystemStateMulti(chain.wallet, config, marketIndexes)(Float__Contracts.convertTxOptions(txOptions));
            });
}

exports.fromInt = fromInt;
exports.wrapChainP = wrapChainP;
exports.wrapChainW = wrapChainW;
exports.WithProvider = WithProvider;
exports.WithWallet = WithWallet;
exports.contracts = contracts;
exports.updateSystemStateMulti = updateSystemStateMulti$1;
/* ethers Not a pure module */
