// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Config = require("./Config.js");
var Ethers = require("./demo/Ethers.js");
var Ethers$1 = require("ethers");
var CONSTANTS = require("./demo/CONSTANTS.js");
var Contracts = require("./demo/Contracts.js");
var Caml_array = require("rescript/lib/js/caml_array.js");
var MarketSide = require("./MarketSide.js");

function div(prim0, prim1) {
  return prim0.div(prim1);
}

function fromInt(prim) {
  return Ethers$1.BigNumber.from(prim);
}

function toNumber(prim) {
  return prim.toNumber();
}

function makeLongShortContract(p, c) {
  return Contracts.LongShort.make(Ethers$1.utils.getAddress(c.contracts.longShort.address), p);
}

function makeStakerContract(p, c) {
  return Contracts.Staker.make(Ethers$1.utils.getAddress(c.contracts.longShort.address), p);
}

function leverage(p, c, marketIndex) {
  return makeLongShortContract(Ethers.wrapProvider(p), c).marketLeverage_e18(marketIndex).then(function (m) {
              return m.div(CONSTANTS.tenToThe18).toNumber();
            });
}

function syntheticTokenPrices(p, c, marketIndex) {
  return Promise.all([
                MarketSide.syntheticTokenPrice(p, c, marketIndex, true),
                MarketSide.syntheticTokenPrice(p, c, marketIndex, false)
              ]).then(function (param) {
              return {
                      long: param[0],
                      short: param[1]
                    };
            });
}

function exposures(p, c, marketIndex) {
  return Promise.all([
                MarketSide.exposure(p, c, marketIndex, true),
                MarketSide.exposure(p, c, marketIndex, false)
              ]).then(function (param) {
              return {
                      long: param[0],
                      short: param[1]
                    };
            });
}

function unconfirmedExposures(p, c, marketIndex) {
  return Promise.all([
                MarketSide.unconfirmedExposure(p, c, marketIndex, true),
                MarketSide.unconfirmedExposure(p, c, marketIndex, false)
              ]).then(function (param) {
              return {
                      long: param[0],
                      short: param[1]
                    };
            });
}

function fundingRateAprs(p, c, marketIndex) {
  return Promise.all([
                MarketSide.fundingRateApr(p, c, marketIndex, true),
                MarketSide.fundingRateApr(p, c, marketIndex, false)
              ]).then(function (param) {
              return {
                      long: param[0],
                      short: param[1]
                    };
            });
}

function positions(p, c, marketIndex, address) {
  return Promise.all([
                MarketSide.positions(p, c, marketIndex, true, address),
                MarketSide.positions(p, c, marketIndex, false, address)
              ]).then(function (param) {
              return {
                      long: param[0],
                      short: param[1]
                    };
            });
}

function stakedPositions(p, c, marketIndex, address) {
  return Promise.all([
                MarketSide.stakedPositions(p, c, marketIndex, true, address),
                MarketSide.stakedPositions(p, c, marketIndex, false, address)
              ]).then(function (param) {
              return {
                      long: param[0],
                      short: param[1]
                    };
            });
}

function unsettledPositions(p, c, marketIndex, address) {
  return Promise.all([
                MarketSide.unsettledPositions(p, c, marketIndex, true, address),
                MarketSide.unsettledPositions(p, c, marketIndex, false, address)
              ]).then(function (param) {
              return {
                      long: param[0],
                      short: param[1]
                    };
            });
}

function claimFloatCustomFor(w, c, marketIndexes, address) {
  var partial_arg = makeStakerContract(Ethers.wrapWallet(w), c);
  return function (param) {
    return partial_arg.claimFloatCustomFor(marketIndexes, address, param);
  };
}

function settleOutstandingActions(w, c, marketIndex, address) {
  var partial_arg = makeLongShortContract(Ethers.wrapWallet(w), c);
  return function (param) {
    return partial_arg.executeOutstandingNextPriceSettlementsUser(address, marketIndex, param);
  };
}

function updateSystemState(w, c, marketIndex) {
  var partial_arg = makeLongShortContract(Ethers.wrapWallet(w), c);
  return function (param) {
    return partial_arg.updateSystemState(marketIndex, param);
  };
}

function makeWithWallet(w, marketIndex) {
  return {
          contracts: Config.getChainConfig(Ethers.wrapWallet(w)).then(function (c) {
                return {
                        longToken: Caml_array.get(c.markets, marketIndex).longToken,
                        shortToken: Caml_array.get(c.markets, marketIndex).shortToken,
                        yieldManager: Caml_array.get(c.markets, marketIndex).yieldManager
                      };
              }),
          getLeverage: (function (param) {
              return Config.getChainConfig(Ethers.wrapWallet(w)).then(function (c) {
                          return leverage(w.provider, c, Ethers$1.BigNumber.from(marketIndex));
                        });
            }),
          getFundingRateMultiplier: (function (param) {
              return Config.getChainConfig(Ethers.wrapWallet(w)).then(function (c) {
                          return MarketSide.fundingRateMultiplier(w.provider, c, Ethers$1.BigNumber.from(marketIndex));
                        });
            }),
          getSyntheticTokenPrices: (function (param) {
              return Config.getChainConfig(Ethers.wrapWallet(w)).then(function (c) {
                          return syntheticTokenPrices(w.provider, c, Ethers$1.BigNumber.from(marketIndex));
                        });
            }),
          getExposures: (function (param) {
              return Config.getChainConfig(Ethers.wrapWallet(w)).then(function (c) {
                          return exposures(w.provider, c, Ethers$1.BigNumber.from(marketIndex));
                        });
            }),
          getUnconfirmedExposures: (function (param) {
              return Config.getChainConfig(Ethers.wrapWallet(w)).then(function (c) {
                          return unconfirmedExposures(w.provider, c, Ethers$1.BigNumber.from(marketIndex));
                        });
            }),
          getFundingRateAprs: (function (param) {
              return Config.getChainConfig(Ethers.wrapWallet(w)).then(function (c) {
                          return fundingRateAprs(w.provider, c, Ethers$1.BigNumber.from(marketIndex));
                        });
            }),
          getPositions: (function (ethAddress) {
              return Config.getChainConfig(Ethers.wrapWallet(w)).then(function (c) {
                          return positions(w.provider, c, Ethers$1.BigNumber.from(marketIndex), ethAddress);
                        });
            }),
          getStakedPositions: (function (ethAddress) {
              return Config.getChainConfig(Ethers.wrapWallet(w)).then(function (c) {
                          return stakedPositions(w.provider, c, Ethers$1.BigNumber.from(marketIndex), ethAddress);
                        });
            }),
          getUnsettledPositions: (function (ethAddress) {
              return Config.getChainConfig(Ethers.wrapWallet(w)).then(function (c) {
                          return unsettledPositions(w.provider, c, Ethers$1.BigNumber.from(marketIndex), ethAddress);
                        });
            }),
          claimFloatCustomFor: (function (ethAddress, txOptions) {
              return Config.getChainConfig(Ethers.wrapWallet(w)).then(function (c) {
                          return claimFloatCustomFor(w, c, [Ethers$1.BigNumber.from(marketIndex)], ethAddress)(txOptions);
                        });
            }),
          settleOutstandingActions: (function (ethAddress, txOptions) {
              return Config.getChainConfig(Ethers.wrapWallet(w)).then(function (c) {
                          return settleOutstandingActions(w, c, Ethers$1.BigNumber.from(marketIndex), ethAddress)(txOptions);
                        });
            }),
          updateSystemState: (function (txOptions) {
              return Config.getChainConfig(Ethers.wrapWallet(w)).then(function (c) {
                          return updateSystemState(w, c, Ethers$1.BigNumber.from(marketIndex))(txOptions);
                        });
            }),
          getSide: (function (param) {
              return MarketSide.makeWithWallet(w, marketIndex, param);
            })
        };
}

function makeWithProvider(p, marketIndex) {
  return {
          contracts: Config.getChainConfig(Ethers.wrapProvider(p)).then(function (c) {
                return {
                        longToken: Caml_array.get(c.markets, marketIndex).longToken,
                        shortToken: Caml_array.get(c.markets, marketIndex).shortToken,
                        yieldManager: Caml_array.get(c.markets, marketIndex).yieldManager
                      };
              }),
          getLeverage: (function (param) {
              return Config.getChainConfig(Ethers.wrapProvider(p)).then(function (c) {
                          return leverage(p, c, Ethers$1.BigNumber.from(marketIndex));
                        });
            }),
          getFundingRateMultiplier: (function (param) {
              return Config.getChainConfig(Ethers.wrapProvider(p)).then(function (c) {
                          return MarketSide.fundingRateMultiplier(p, c, Ethers$1.BigNumber.from(marketIndex));
                        });
            }),
          getSyntheticTokenPrices: (function (param) {
              return Config.getChainConfig(Ethers.wrapProvider(p)).then(function (c) {
                          return syntheticTokenPrices(p, c, Ethers$1.BigNumber.from(marketIndex));
                        });
            }),
          getExposures: (function (param) {
              return Config.getChainConfig(Ethers.wrapProvider(p)).then(function (c) {
                          return exposures(p, c, Ethers$1.BigNumber.from(marketIndex));
                        });
            }),
          getUnconfirmedExposures: (function (param) {
              return Config.getChainConfig(Ethers.wrapProvider(p)).then(function (c) {
                          return unconfirmedExposures(p, c, Ethers$1.BigNumber.from(marketIndex));
                        });
            }),
          getFundingRateAprs: (function (param) {
              return Config.getChainConfig(Ethers.wrapProvider(p)).then(function (c) {
                          return fundingRateAprs(p, c, Ethers$1.BigNumber.from(marketIndex));
                        });
            }),
          getPositions: (function (ethAddress) {
              return Config.getChainConfig(Ethers.wrapProvider(p)).then(function (c) {
                          return positions(p, c, Ethers$1.BigNumber.from(marketIndex), ethAddress);
                        });
            }),
          getStakedPositions: (function (ethAddress) {
              return Config.getChainConfig(Ethers.wrapProvider(p)).then(function (c) {
                          return stakedPositions(p, c, Ethers$1.BigNumber.from(marketIndex), ethAddress);
                        });
            }),
          getUnsettledPositions: (function (ethAddress) {
              return Config.getChainConfig(Ethers.wrapProvider(p)).then(function (c) {
                          return unsettledPositions(p, c, Ethers$1.BigNumber.from(marketIndex), ethAddress);
                        });
            }),
          getSide: (function (isLong) {
              return MarketSide.makeWithProvider(p, marketIndex, isLong);
            }),
          connect: (function (w) {
              return makeWithWallet(w, marketIndex);
            })
        };
}

exports.div = div;
exports.fromInt = fromInt;
exports.toNumber = toNumber;
exports.makeLongShortContract = makeLongShortContract;
exports.makeStakerContract = makeStakerContract;
exports.leverage = leverage;
exports.syntheticTokenPrices = syntheticTokenPrices;
exports.exposures = exposures;
exports.unconfirmedExposures = unconfirmedExposures;
exports.fundingRateAprs = fundingRateAprs;
exports.positions = positions;
exports.stakedPositions = stakedPositions;
exports.unsettledPositions = unsettledPositions;
exports.claimFloatCustomFor = claimFloatCustomFor;
exports.settleOutstandingActions = settleOutstandingActions;
exports.updateSystemState = updateSystemState;
exports.makeWithWallet = makeWithWallet;
exports.makeWithProvider = makeWithProvider;
/* Config Not a pure module */
